/**
 * Legacy Expo Audio registry for the native crossfade mixer. These pre-existing
 * key loops remain for native compatibility; the browser's multisampler fetches
 * pad samples from public URLs and uses sampleRegistry.ts only for local beds.
 *
 * Keep these static requires until the native player is migrated to the
 * multisample engine. This registry is not generated by an app script.
 */

import type { MusicalKey, PitchedStem, TextureId } from '../../types/audio';

export type AudioModule = number;

export const PAD_LIBRARY: Record<MusicalKey, Record<PitchedStem, AudioModule>> = {
  'C': {
    base: require('./pads/C/base.wav'),
    shimmer: require('./pads/C/shimmer.wav'),
    sub: require('./pads/C/sub.wav'),
  },
  'C#': {
    base: require('./pads/Cs/base.wav'),
    shimmer: require('./pads/Cs/shimmer.wav'),
    sub: require('./pads/Cs/sub.wav'),
  },
  'D': {
    base: require('./pads/D/base.wav'),
    shimmer: require('./pads/D/shimmer.wav'),
    sub: require('./pads/D/sub.wav'),
  },
  'D#': {
    base: require('./pads/Ds/base.wav'),
    shimmer: require('./pads/Ds/shimmer.wav'),
    sub: require('./pads/Ds/sub.wav'),
  },
  'E': {
    base: require('./pads/E/base.wav'),
    shimmer: require('./pads/E/shimmer.wav'),
    sub: require('./pads/E/sub.wav'),
  },
  'F': {
    base: require('./pads/F/base.wav'),
    shimmer: require('./pads/F/shimmer.wav'),
    sub: require('./pads/F/sub.wav'),
  },
  'F#': {
    base: require('./pads/Fs/base.wav'),
    shimmer: require('./pads/Fs/shimmer.wav'),
    sub: require('./pads/Fs/sub.wav'),
  },
  'G': {
    base: require('./pads/G/base.wav'),
    shimmer: require('./pads/G/shimmer.wav'),
    sub: require('./pads/G/sub.wav'),
  },
  'G#': {
    base: require('./pads/Gs/base.wav'),
    shimmer: require('./pads/Gs/shimmer.wav'),
    sub: require('./pads/Gs/sub.wav'),
  },
  'A': {
    base: require('./pads/A/base.wav'),
    shimmer: require('./pads/A/shimmer.wav'),
    sub: require('./pads/A/sub.wav'),
  },
  'A#': {
    base: require('./pads/As/base.wav'),
    shimmer: require('./pads/As/shimmer.wav'),
    sub: require('./pads/As/sub.wav'),
  },
  'B': {
    base: require('./pads/B/base.wav'),
    shimmer: require('./pads/B/shimmer.wav'),
    sub: require('./pads/B/sub.wav'),
  },
};

export const TEXTURE_LIBRARY: Record<TextureId, AudioModule> = {
  vinyl: require('./textures/vinyl.wav'),
  rain: require('./textures/rain.wav'),
  room: require('./textures/room.wav'),
};

/** Length of the pre-existing native compatibility loops, in seconds. */
export const LOOP_LENGTH_SECONDS = 6;
